module.exports = {
  PHONE_EMPTY_ERROR: "Phone number can't be empty.",
  PHONE_LENGTH_ERROR: 'Invalid phone number',
  PASSWORD_ERROR: "Password can't be empty",
  MATCH_ERROR: 'Password do not Match',
  CODE_ERROR: "Code can't be empty",
  CREDIANTIAL_ERROR: 'Invalid Crediantials',
  INCOMPLETE_PASSWORD: 'Password is incorrect',
  MINIMUM_PASSWORD:
    'Password must be atleast 8 characters, with one letter, one number and one special character',
  MATCH_PASSWORD: 'Password does not match',
  EMPTY_NAME: "Name can't be empty",
  EMPTY_OCCUPATION: "Occupation can't be empty",
  EMPTY_PHONE: "Phone Number can't be empty",
  EMPTY_EMAIL: "EMail can't be empty",
  EMPTY_BIRTHDAY: "Birthday can't be empty",
  EMPTY_ADDRESS: "Address can't be empty",
  EMPTY_CITY: "City can't be empty",
  EMPTY_COUNTRY: "COuntry can't be empty",
  EMPTY_MESSAGE: "Message can't be empty",
  EMPTY_QRCODE: "QR Code can't be empty",
  EMPTY_HOBBIES: "Hobbies can't be empty",
  EMPTY_EDUCATION: "Education can't be empty",
  EMPTY_INTERESTS: "Interests can't be empty",
  EMPTY_ACHIVEMENT: "Achivements can't be empty",
  EMPTY_PERSONALINFO: "Personal Info can't be empty",
  EMPTY_SKILLS: "Skills can't be empty",
  EMPTY_PORTFOLIO: "PortFolio can't be empty",
  EMPTY_JOBHISTORY: "Job History can't be empty",
  EMPTY_TYPE: "Product Shelving can't be empty",
  EMPTY_LOCATION: "Services Offered can't be empty",
  EMPTY_LOGO: "Hourly Vage can't be empty",
  EMPTY_BUSINESS: "Busines Industry can't be empty",
  EMPTY_INCORPORATION: "Date of Incorporation can't be empty",
  EMPTY_PORTFOLIO: "PortFolio can't be empty",
  EMPTY_WEBSITE: "Company Website can't be empty",
  EMPTY_CATEGORY: 'Category details cannot be empty',
  EMPTY_PRODUCT: 'Product details cannot be empty',
  EMPTY_OTHERINFO: 'Other Info cannot be empty',
  EMPTY_TAGLINE: 'Tagline cannot be empty',
};
